#  ----------网站基础信息维护-----------------
# The URL the site will be built for
base_url = "https://widowmaker2025.github.io/"
title = "Widomaker"
description = "黑百合的博客"
default_language = "en"   # 不支持国际化/翻译，但您可以为您的网站设置 HTML 语言代码

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

#  -------------RSS 订阅 部分设置------------ 
# The theme supports feeds (RSS and ATOM) 支持订阅
generate_feeds = true
# Use `rss.xml` for RSS feeds and `atom.xml` for ATOM.
feed_filenames = ["rss.xml", "atom.xml"]


# Optional: enable tags  启用标签
# 启用标签将创建一个新/tags页面，并使其显示在archive版块中。请注意，您仍然需要手动创建指向标签页面的菜单链接。
taxonomies = [
    {name = "tags"}
]


# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true       #启用代码高亮
highlight_theme = "boron"   



[extra]
# Put all your custom variables here

# One of: blue, green, orange, pink, red.
# Defaults to blue.
# Append -light for light themes, e.g. blue-light
# Or append -auto, e.g. blue-auto
accent_color = "green"

# One of: blue, dark, green, orange, pink, red, light, auto
# Enabling dark background will also modify primary font color to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "dark"

# The logo text - defaults to "Terminimal theme"
logo_text = "⭐Widowmake⭐"

# The logo link - defaults to base_url.
logo_home_link = "/"

# 作者 版权信息 
# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "Rocky.houjinsong"

# Copyright text in HTML format. If specified,
# entirely replaces default copyright and author.
#copyright_html = "My custom&nbsp;<b>copyright</b>"

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "Blog", url = "$BASE_URL", image = "https://www.istockphoto.com/vector/book-icon-gm863958484-143332491?utm_source=pixabay&utm_medium=affiliate&utm_campaign=sponsored_vector&utm_content=srp_topbanner_media&utm_term=books"}, #TODO 博客路由
    {name = "Book", url = "$BASE_URL"},   #TODO 书评书摘路由
    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    {name = "Tags ", url = "$BASE_URL/tags"},
    {name = "Archive", url = "$BASE_URL/archive"},
    {name = "about me |关于我", url = "$BASE_URL/about"},

    # set newtab to true to make the link open in new tab
    {name = "github", url = "https://github.com/Widowmaker2025", newtab = true},
]

# 调整主题的分页配置
# Whether to show links to earlier and later (aka. higher/lower) posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# 默认情况下，主题使用 Hack 字体的混合子集。普通粗细字体使用完整字符集
#（用于 Unicode 图标和特殊符号），但所有其他字体（粗体、斜体等）均使用有限的子集。
# 这会导致传输大小变得更小，但子集可能不包含您需要的所有 Unicode 字符
# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.

use_full_hack_font = true

# 该主题支持向网站添加全局图标（适用于所有页面）
# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
# favicon = "/favicon.png"
# favicon_mimetype = "image/png"

# 主题允许您配置页面标题（<title>元素）的呈现方式
# 用于"combined"将标题呈现为"Page title | Main title"
# Optional: Set how <title> elements are rendered.
# Values:
# - "main_only" -- only the main title (`config.title`) is rendered.
# - "page_only" -- only the page title (if defined) is rendered,
#                  falling back to `config.title` if not defined or empty.
# - "combined" -- combine like so: "page_title | main_title",
#                 or if page_title is not defined or empty, fall back to `main_title`
#
# Note that the main (index) page only has the main title.
page_titles = "combined"

# Optional: default image to use for OpenGraph.
#           If the page doesnt set og_image, use this one as fallback. Usefull
#           for indexes and taxonomies' pages.
#default_og_image = "static/ocean.jpg"
# 要将图像添加到帖子中，请将og_image额外选项设置为 markdown 文件的同一目录中的所需图像
og_image = "colocated_image.png"
# 部分页面和帖子，要有后备图像，请 在部分default_og_image中添加[extra]
default_og_image = "static/ocean.jpg"

# 显示帖子描述
show_only_description = true
